server:
  port: 8123
  servlet:
    context-path: /api
    #cookie30天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: sr-picture-backend
  profiles:
    active: local
  datasource:
    driver-class-name: ${sr.datasource.driver-class-name}
    url: ${sr.datasource.url}
    username: ${sr.datasource.username}
    password: ${sr.datasource.password}
  redis:
    database: 0
    host: ${sr.redis.host}
    port: ${sr.redis.port}
    timeout: 5000
  #session配置
  session:
    store-type: redis
    #30天过期
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
#  shardingsphere:
#    mode:
#      type: Standalone
#      repository:
#        type: JDBC
#    datasource:
#      names: yu-picture
#      yu-picture:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: ${sr.datasource.driver-class-name}
#        url: ${sr.datasource.url}
#        username: ${sr.datasource.username}
#        password: ${sr.datasource.password}
#    rules:
#      sharding:
#        tables:
#          picture:
#            actual-data-nodes: yu-picture.picture
#            table-strategy:
#              standard:
#                sharding-column: spaceId
#                sharding-algorithm-name: picture_sharding_algorithm
#        sharding-algorithms:
#          picture_sharding_algorithm:
#            type: CLASS_BASED
#            props:
#              strategy: standard
#              algorithmClassName: com.tuque.srpicturebackend.manager.sharding.PictureShardingAlgorithm
#    props:
#      sql-show: true
#mabatis-plus配置
mybatis-plus:
    configuration:
        #禁止驼峰命名转换，数据库字段和实体类属性保持一致
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #仅在开发环境打印日志
    global-config:
       enable-sql-runner: true
       db-config:
          logic-delete-field: isDelete #全局逻辑删除字段名
          logic-delete-value: 1 #全局逻辑删除值（表示已删除）
          logic-not-delete-value: 0 #全局逻辑未删除值（表示未删除）
#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.tuque.srpicturebackend.controller
#对象存储配置（腾讯云）
cos:
  client:
    host: ${sr.client.host}
    secretId: ${sr.client.secretId}
    secretKey: ${sr.client.secretKey}
    region: ${sr.client.region}
    bucket: ${sr.client.bucket}
#阿里云ai配置
aliYunAi:
  apiKey: ${sr.aliYunAi.apiKey}
#LangChain4j配置
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${sr.aliYunAi.apiKey}
        model-name: qwen-plus
picture:
  search:
    vector-enabled: true
