server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: yu-picture-backend
  profiles:
    active: local
  datasource:
    driver-class-name: ${sr.datasource.driver-class-name}
    url: ${sr.datasource.url}
    username: ${sr.datasource.username}
    password: ${sr.datasource.password}
#mabatis-plus配置
mybatis-plus:
    configuration:
        #禁止驼峰命名转换，数据库字段和实体类属性保持一致
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #仅在开发环境打印日志
    global-config:
        db-config:
          logic-delete-field: isDelete #全局逻辑删除字段名
          logic-delete-value: 1 #全局逻辑删除值（表示已删除）
          logic-not-delete-value: 0 #全局逻辑未删除值（表示未删除）
#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller
#对象存储配置（腾讯云）
cos:
  client:
    host: ${sr.client.host}
    secretId: ${sr.client.secretId}
    secretKey: ${sr.client.secretKey}
    region: ${sr.client.region}
    bucket: ${sr.client.bucket}